# Generated by Django 3.2.4 on 2021-06-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_dated', models.DateTimeField(verbose_name='data published')),
                ('body', models.TextField()),
            ],
        ),
    ]
