# Generated by Django 3.2.4 on 2021-06-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='genre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
