# Generated by Django 3.2.2 on 2021-05-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldmanblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oldman_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_title', models.CharField(max_length=100)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('body', models.TextField()),
                ('data_link', models.CharField(max_length=200)),
            ],
        ),
    ]
